name: Build and Upload Bundles to S3

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Run Build
    uses: ads102003/Actions/.github/workflows/game-build.yml@main
    with:
      game: "ReignOfKings"
      branch-postfix: "-${{ github.ref_name }}"
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  deploy:
    name: Deploy to S3
    uses: ads102003/Actions/.github/workflows/r2-publish.yml@main
    needs: build
    with:
      generate-filehash: true
    secrets:
      CLOUDFLARE_R2_KEY: ${{ secrets.CLOUDFLARE_R2_KEY }}
      CLOUDFLARE_R2_SECRET: ${{ secrets.CLOUDFLARE_R2_SECRET }}
      CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
